### ISSUE TITLE
Adding mockdata for insights

### ISSUE THREAD

**Issue by mk4111** [emfoundation/mock-data#1]
Need to add mockdata for insights. These insights should have the following information:

- title (text)
- url (text)
- type of document (text)
- author (text input)
- resources (boolean)
- active = enable/disable (true)
- creator_id (number)
- org_id  (number)
- date (postgres date format)

If an insight has a tag or tags attached to it, they will be stored in the tags_insights table.

**Comment by mk4111** [comment]
I have created 3 mock insight entries:
- Insight Number 1 is enabled, is a resource and has tags
- Insight Number 2 is not enabled, is a resource and has no tags
- Insight Number 3 is enabled, is not a resource and has 1 tag

**Comment by SimonLab** [comment]
resolved with #2
