### ISSUE TITLE
Update tags_organisations.json

### ISSUE THREAD

**Issue by mk4111** [emfoundation/mock-data#4]
We are currently using `primary_3` (indicating primary user, who has id = 3) to test primary user views with.
The issue is that the organisation (id=1) attached to `primary_3`, does not share a tag in common with any of the other organisations, so when testing for suggested matches ([as can be seen in this PR](https://github.com/emfoundation/ce100-app/pull/506)) we are returned with no matches.

We need to update tags_organisations.json so that organisation (id = 1) can have suggested matches.

**Comment by SimonLab** [comment]
resolved with #3
